#ifndef __MNIVERTSTATSFILE__
#define __MNIVERTSTATSFILE__

#include <vector>
#include <iostream>
#include <fstream>
#include <string>

using namespace std;

/*! A class to read vertex statistics files
 * 
 * A class designed to read and interact with vertex statistics files
 * as generated by the vertex based morphometry techniques. These
 * files contain the following elements: a header, containing the
 * formula used to generate the data, statistics performed on the
 * mean, etc., and a body containing the actual statistical elements
 * in a m*n matrix, where m is the number of vertices and n is the
 * number of statistical terms *(F stats, adjusted R square, etc.).
 */

class mniVertstatsFile {
private:
  string *mean;
  string *formula;
  vector <string> *matrix;
  vector <string> *dataheader;
public:
  mniVertstatsFile(char *filename);
};

#endif // __MNIVERTSTATSFILE__
